### ISSUE TITLE
installing from sources: "RuntimeError: Unable to find the MKL library in the conda distribution used."

### ISSUE THREAD

**Issue by jerabaul29** [CNES/pangeo-pytide#4]
Hi,

I am trying to install from source and compile following the instructions at:

https://pangeo-pytide.readthedocs.io/en/latest/setup.html

I am on Ubuntu 20.04, Python 3.8.2, I have run the commands for installing both Eigen3 and numpy as described there.

However, I still get the following problem:

```
> python3 setup.py build
running build
running build_py
copying src/pytide/version.py -> build/lib.linux-x86_64-3.8/pytide
running build_ext
Traceback (most recent call last):
  File "setup.py", line 353, in <module>
    main()
  File "setup.py", line 320, in main
    setuptools.setup(name='pytide',
  File "/home/jrmet/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 316, in run
    super().run()
  File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 166, in run
    self.build_cmake(ext)
  File "setup.py", line 249, in build_cmake
    ] + self.set_cmake_user_options()
  File "setup.py", line 231, in set_cmake_user_options
    self.mkl()
  File "setup.py", line 196, in mkl
    raise RuntimeError(
RuntimeError: Unable to find the MKL library in the conda distribution used.
```

and similarly:

```
> python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing src/pytide.egg-info/PKG-INFO
writing dependency_links to src/pytide.egg-info/dependency_links.txt
writing requirements to src/pytide.egg-info/requires.txt
writing top-level names to src/pytide.egg-info/top_level.txt
reading manifest file 'src/pytide.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'third_party'
warning: no files found matching '*' under directory 'cmake'
warning: no previously-included files matching '*.py[dco]' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
no previously-included directories found matching 'docs/build'
writing manifest file 'src/pytide.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 353, in <module>
    main()
  File "setup.py", line 320, in main
    setuptools.setup(name='pytide',
  File "/home/jrmet/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/jrmet/.local/lib/python3.8/site-packages/setuptools/command/test.py", line 231, in run
    with self.project_on_sys_path():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/jrmet/.local/lib/python3.8/site-packages/setuptools/command/test.py", line 150, in project_on_sys_path
    self.run_command('build_ext')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 166, in run
    self.build_cmake(ext)
  File "setup.py", line 249, in build_cmake
    ] + self.set_cmake_user_options()
  File "setup.py", line 231, in set_cmake_user_options
    self.mkl()
  File "setup.py", line 196, in mkl
    raise RuntimeError(
RuntimeError: Unable to find the MKL library in the conda distribution used.
```

I tried to install mkl with:

```sudo apt install intel-mkl-full```

but this did not help either.

Any recommendations?

**Comment by jerabaul29** [comment]
I installed with conda instead and that works fine, but still, I may want to use a compile from source approach if this would be possible :) .

**Comment by fbriol** [comment]
You have just to install the MKL distribution provided by conda

```
conda install mkl
```

**Comment by jerabaul29** [comment]
Ah yes that's a good idea, compiling from source but within conda. Ok, will do that :)

**Comment by fbriol** [comment]
I got the wrong package:

```
conda install mkl-devel
```
